sudo: required
language: go
go_import_path: github.com/ethereum/go-ethereum

jobs:
  include:

  - stage: Lint
    sudo: false
    go: '1.10'
    git:
      submodules: false
      script:
        - go run build/ci.go lint

  - stage: Build and test
    go: '1.11'
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - while sleep 540; do echo "[ still running ]"; done &
    - go run build/ci.go test -coverage
    - kill %1
  - go: '1.10'
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - while sleep 540; do echo "[ still running ]"; done &
    - go run build/ci.go test -coverage
    - kill %1

  - stage: Github release
    go: '1.10'
    script:
      - make tyslin
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      file:
        - "build/bin/tyslin"
      skip_cleanup: true
      on:
        branch: master
        tags: true

  - stage: Build and push image
    services:
      - docker
    install: skip
    before_script:
      - docker build -t tyslinchain/tyslinchain .
      - docker build -t tyslinchain/node -f Dockerfile.node .
    script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag tyslinchain/tyslinchain tyslinchain/tyslinchain:latest
      - docker push tyslinchain/tyslinchain:latest
      - docker tag tyslinchain/tyslinchain tyslinchain/tyslinchain:$TRAVIS_BUILD_ID
      - docker push tyslinchain/tyslinchain:$TRAVIS_BUILD_ID
      - docker tag tyslinchain/node tyslinchain/node:latest
      - docker push tyslinchain/node:latest
      - docker tag tyslinchain/node tyslinchain/node:$TRAVIS_BUILD_ID
      - docker push tyslinchain/node:$TRAVIS_BUILD_ID

  - stage: Build and push image (tagged)
    services:
      - docker
    install: skip
    before_script:
      - docker build -t tyslinchain/tyslinchain .
      - docker build -t tyslinchain/tyslinchain -f Dockerfile.node .
    script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag tyslinchain/tyslinchain tyslinchain/tyslinchain:latest
      - docker push tyslinchain/tyslinchain:latest
      - docker tag tyslinchain/tyslinchain tyslinchain/tyslinchain:$TRAVIS_TAG
      - docker push tyslinchain/tyslinchain:$TRAVIS_TAG
      - docker tag tyslinchain/tyslinchain tyslinchain/node:latest
      - docker push tyslinchain/node:latest
      - docker tag tyslinchain/node tyslinchain/node:$TRAVIS_TAG
      - docker push tyslinchain/node:$TRAVIS_TAG

stages:
  - name: Lint
  - name: Build and test
  - name: Github release
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = tyslinchain/tyslinchain
  - name: Build and push image
    if: type != pull_request AND branch = master AND tag IS blank AND repo = tyslinchain/tyslinchain
  - name: Build and push image (tagged)
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = tyslinchain/tyslinchain

notifications:
  slack:
    rooms:
      secure: DoWVSWEKZre0rsYvHPqOBpYa5hL7DagVCP7eGR+2dluzsyUOTW58uiaezaZMAPPG6k7i1TC9CufONkFRwH6kqLrFtAFd+t3sKb3X4D9/PSa9k88uBuNfsX+JhUzEMT53pfLO9NTBbZs3M6bOuZDP7GddWWnMZpO6Mu7RzZtVxyqbZIcNu3nxsmLkoaQ8726npaHrxhO1Ab+3rgR4dkNFLgl9/CnPwvuv/j24dsKzly6tF+4Ms9Fz5O0Te8zK5d/UWZN50e+uDnbzcIvbY2VHOYXchXZRbfKO8/M2TIXLPKbLc3alCw1ZvpFZqiMYK3SnGNby4FLp8RlC6H4sv52YeNq3fHH8SgOJ3xTL8m6ejIlqoKnUNsJ1lwtfiEVu5D1b8FRKTPqoh+cjadJxsF9dO0xZsf1d5Pmq6Ncr0j6di1ZMjCc6TPFERxkdA48+PzQY4TqfBpM4E5RnJuX9O9MJFbA1fZo2xhHcy0LlkslZMpSwiv/YO4bCJZPmxvHtruqELJXxjYyC67UbzSzrBVE1g1bXy0V5xyxPIEA38jzlNczhq6fg2gyEc+6JCbzN2gFoAS5uFWQHpUhXHc7zNB5Jyi7GPQv6cfHYcedjn9In9/bNDqqGexGX4Ih/cb6W1GOHC7c2A/AsfTa9KWmsyj7YwBRXFIXfme7bBh6VGuRqU3Y=
    on_success: change
    on_failure: always
